<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://centipede.com" xmlns:apachesoap="http://xml.apache.or"></wsdl:definitions> 
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
<schema elementFormDefault="qualified" targetNamespace="http://centipede.com" xmlns="http://www
 <element name="getPrefix">
<complexType>
     <sequence>
      <element name="_prefix" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="getPrefixResponse">
    <complexType>
     <sequence>
      <element name="getPrefixReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>
   <wsdl:message name="getPrefixResponse">
      <wsdl:part element="impl:getPrefixResponse" name="parameters">
      </wsdl:part>
   </wsdl:message>
   <wsdl:message name="getPrefixRequest">
      <wsdl:part element="impl:getPrefix" name="parameters">
      </wsdl:part>
   </wsdl:message>
   <wsdl:portType name="Getplace">
      <wsdl:operation name="getPrefix">
         <wsdl:input message="impl:getPrefixRequest" name="getPrefixRequest">
       </wsdl:input>
         <wsdl:output message="impl:getPrefixResponse" name="getPrefixResponse">
       </wsdl:output>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="GetplaceSoapBinding" type="impl:Getplace">
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="getPrefix">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getPrefixRequest">
            <wsdlsoap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="getPrefixResponse">
            <wsdlsoap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="GetplaceService">
      <wsdl:port binding="impl:GetplaceSoapBinding" name="Getplace">
         <wsdlsoap:address location="http://localhost:8080/Centipede/services/Getplace"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>